version: '3.8'

services:
  app:
    container_name: ssl-portal
    build:
      context: .
      args:
        - NPM_TOKEN=${NPM_TOKEN}
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 5173:5173
    env_file:
      - .env
      - .env.development
