// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutView: typeof import('./views/AboutView.vue')['default']
    DashboardView: typeof import('./views/DashboardView.vue')['default']
    ErrorHeader: typeof import('./@core/components/ErrorHeader.vue')['default']
    HomeView: typeof import('./views/HomeView.vue')['default']
    LoginView: typeof import('./views/LoginView.vue')['default']
    MyAlert: typeof import('./components/MyAlert/MyAlert.vue')['default']
    NewPasswordView: typeof import('./views/NewPasswordView.vue')['default']
    RegisterView: typeof import('./views/RegisterView.vue')['default']
    ResetPasswordView: typeof import('./views/ResetPasswordView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stepper: typeof import('./components/Stepper/Stepper.vue')['default']
  }
}
